[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stunning-train"
version = "0.2.0"
description = "A terminal-based Rapid Serial Visual Presentation (RSVP) fast screen reader."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pypdf",
    "rich"
]

[project.scripts]
stt = "stunning_train.cli:run"

[tool.setuptools.packages.find]
where = ["src"]
